####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  sandbox-postgres-data:
    driver: local

  # MySQL Data
  simplecrm-mysql-data:
    driver: local

  # Redis Data
  simplecrm-redis-data:
    driver: local

services:
  # Postgres (9.5)
  postgres:
    image: ambientum/postgres:9.6
    container_name: sandbox-postgres
    volumes:
      - sandbox-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_DB=sandbox
      - POSTGRES_USER=sandbox

  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: simplecrm-mysql
    volumes:
      - simplecrm-mysql-data:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=simplecrm
      - MYSQL_DATABASE=simplecrm
      - MYSQL_USER=simplecrm
      - MYSQL_PASSWORD=simplecrm

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: simplecrm-redis
    command: --appendonly yes
    volumes:
      - simplecrm-redis-data:/data
    ports:
      - "6379:6379"

  # Simple CRM Api (with Caddy)
  api:
    image: ambientum/php:7.0-caddy
    container_name: simplecrm-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: simplecrm-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache
